#ifndef ALNS_INC_H_
#define ALNS_INC_H_

#include "alns/acceptanceModule/CoolingScheduleFactory.h"
#include "alns/acceptanceModule/CoolingSchedule_Parameters.h"
#include "alns/acceptanceModule/ExponentialCoolingSchedule.h"
#include "alns/acceptanceModule/IAcceptanceModule.h"
#include "alns/acceptanceModule/ICoolingSchedule.h"
#include "alns/acceptanceModule/SimulatedAnnealing.h"
#include "alns/acceptanceModule/DummyAcceptanceModule.h"
#include "alns/improvedALNS/ANodeDestroyOperator.h"
#include "alns/improvedALNS/ANodeRepairOperator.h"
#include "alns/improvedALNS/APathDestroyOperator.h"
#include "alns/improvedALNS/APathRepairOperator.h"
#include "alns/improvedALNS/Node_Null_Destroy.h"
#include "alns/improvedALNS/Node_Null_Repair.h"
#include "alns/improvedALNS/Path_Null_Destroy.h"
#include "alns/improvedALNS/Path_Null_Repair.h"
#include "alns/improvedALNS/ALNS_Iteration_Status.h"
#include "alns/improvedALNS/ALNS_Parameters.h"
#include "alns/improvedALNS/ALNS.h"
#include "alns/improvedALNS/AOperator.h"
#include "alns/improvedALNS/AStrategyManager.h"
#include "alns/improvedALNS/IBestSolutionManager.h"
#include "alns/improvedALNS/ISolution.h"
#include "alns/improvedALNS/IUpdatable.h"
#include "alns/improvedALNS/StrategyManager.h"
#include "alns/improvedALNS/SimpleBestSolutionManager.h"
#include "alns/localsearch/ILocalSearch.h"
#include "alns/localsearch/ILocalSearchManager.h"
#include "alns/localsearch/SimpleLocalSearchManager.h"
#include "alns/statistics/Statistics.h"
// #include "alns/acceptanceModule/LinearCoolingSchedule.h"
// #include "alns/acceptanceModule/MixLinearCoolingSchedule.h"
// #include "alns/acceptanceModule/TimeLinearCoolingSchedule.h"
// #include "alns/acceptanceModule/CoolingScheduleParametersOptimizable.h"
// #include "alns/improvedALNS/ALNSParametersoptimizable.h"
// #include "alns/tuning/ISolverBuilder.h"
// #include "alns/tuning/ParameterTuning.h"

#endif

